---
title: "melting_analysis_template"
author: "T.PAREE, R.ALARCON,D.WANG"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,  
                      message = FALSE,
                      warning = FALSE)

```

# set path and import function

```{r}
library(dplyr)
path <- '/Users/robinalarcon/Desktop/stage IBENS/qPCR melting curves/melting curves'

# ANALYSE THE MELTING CURVES AND EXTRACT METRICS #

# Import function; 
# all package on the function_melting_analysis.R must be installed
source(paste0('/Users/robinalarcon/Desktop/stage IBENS/qPCR melting curves/melting curves/function_melting_analysis_volcano.R'))
```

# read data

## PCR plate design

```{r}
# Import design (samples details and their corresponding qPCR well)
design_volcano = read_xlsx(paste0("block2_volcano_long.xlsx"))
```

## Melting cuurve

```{r}
# Import melting curve data (melting_example.txt; fluorescence ~ temperature, for each well) and format them.
# To obtain the melting_example.txt file in the Roche480 software, 
# you go into melting curve analysis and right-click on the melting curve figures 
# => export data => .txt

rawd_volcano1 = readHRM(paste0("02062026_DWRA_volcano_plate1_meltingcurve.txt"))
rawd_volcano2 = readHRM(paste0("02062026_DWRA_volcano_plate2_meltingcurve.txt"))
```

## amplification curve

```{r}
# Import and format the amplification phase data (ampli_example.txt)
# This file is only used to filter out samples with falied/weird amplification
# To obtain "ampli_example.txt" in the Roche480 software, you right-click on the amplification phase figure => export data => .txt

df_volcano1 <- read.table("02062026_DWRA_volcano1_amplicurve.txt", header = TRUE, sep = "\t")
write.table(df_volcano1, "02062026_DWRA_volcano_plate1_amplicurve.txt", sep = "\t", dec = ",", row.names = FALSE)
ampli_volcano1 = readAmpli("02062026_DWRA_volcano_plate1_amplicurve.txt")

df_volcano2 <- read.table("02062026_DWRA_volcano2_amplicurve.txt", header = TRUE, sep = "\t")
write.table(df_volcano2, "02062026_DWRA_volcano_plate2_amplicurve.txt", sep = "\t", dec = ",", row.names = FALSE)
ampli_volcano2 = readAmpli("02062026_DWRA_volcano_plate2_amplicurve.txt")

```

# curve

```{r}
library(dplyr)
ampli_curve_volcano <- ampli_volcano1 %>%
  left_join(design_volcano, by = join_by(well_pcr))
melt_curve_volcano <- rawd_volcano1 %>%
  left_join(design_volcano, by = join_by(well_pcr))


ggplot(ampli_curve_volcano, aes(x = cycle, y = fluo, group = well_pcr, color = generation)) +
  facet_wrap(~ pop)+
  geom_line()
ggplot(melt_curve_volcano, aes(x = temp, y = fluo, group = well_pcr, color = generation)) +
  facet_wrap(~pop)+
  geom_line()
```

### set id for each well

```{r}
# Not necessary if only one qPCR plate
rawd_volcano1$plate_qpcr_id = "plate1"
ampli_volcano1$plate_qpcr_id = "plate1"

rawd_volcano2$plate_qpcr_id = "plate2"
ampli_volcano2$plate_qpcr_id = "plate2"

# to bind several plates (If so, must have a plate_qpcr_id):
rawd_volcano=rbind(rawd_volcano1, rawd_volcano2)
ampli_volcano = rbind(ampli_volcano1, ampli_volcano2)

# Must have a unique identifier for each well (well x plate)
rawd_volcano$id = paste0(rawd_volcano$plate_qpcr_id,"#",rawd_volcano$well_pcr)
ampli_volcano$id = paste0(ampli_volcano$plate_qpcr_id,"#",ampli_volcano$well_pcr)
```

# Normalize the raw melting curve

```{r}
#### HRM is the main function
# It normalizes the raw melting curve
# Search for the different melting phase
# Extract few metrics from the curve that can be then used to infer the rec-1 mutant frequency and to filter abnormal curves
# (!) A lot of warnings are expected (empry well or failed amplification usually). Don't worry.

# New temperature ranges are estimated for the Volcano strains from a previous melting test:
trange.mut=c(80.5, 82)
trange.wt=c(82, 83.5)


normd_volcano = HRM(rawd_volcano, ampli_volcano, trange.mut= trange.mut, trange.wt=trange.wt)

#### normd is a list of three elements:

#### normd[[1]] contain the melting curves (raw and normalized).
#temp   well_pcr     fluo      plate_qpcr_id        id       normfluo    normfluoEBS      deriv
#59.51    A1       10.75183        plate1        plate1#A1      100           100      0.08154002
#fluo = raw fluorescence;
#normfluo = normalized fluorescence (basic); normfluoEBS = normalized fluo by EBS (better in theory) 
#=> see "High resolution melting curve analysis with MATLAB-based program", Li, 2016 for details of these methods.
# deriv in the derivative of the raw fluo (i.e., melting peaks)

#### normd[[2]] contains the extracted metrics from the curves
#id         Tbf   Taf   raw.decrease  norm.decrease   normEBS.decrease   het.decrease   plateau_slope      maxfluo
#plate1#A1 73.40 83.52    0.2921659     0.1983239        0.2587710       7.389785      0.0000000000    10.629590
#Taf & Tbf: are the temperatures before and after melting detected by the algorithm
# xxx.decrease: The proportion of a fluorescence decrease during melting attributed to the rec-1 mutant by the algorithm.
# xxx.decrease can be obtained from the different curves (raw or normalized). Usually I used "normEBS.decrease" to infer rec-1 mutant frequency
# het.decrease is the decrease of fluorescence during the heteroduplex melting. This is only used to detect outlier curves.
# plateau_slope is the slope at the end of amplification (did amplification reach a plateau). This is only used to detect outlier curves.
# maxfluo is the fluo after amplification / before melting.  This is only used to detect outlier curves.

#### normd[[3]] contains temperatures delimiting each melting phase (heteroduplex, wt, mut) for each curve.
# start  inflex.bf  peak    inflex.af   end   phase.genotype phase.genotype.score raw.decrease norm.decrease   normEBS.decrease         id
# 73.40     75.59   76.30     76.79     77.08      het                    1        1.3088392      5.818178        10.75188        plate1#A1
# five first column are different landmark of each melting peaks (not very important for you)
# phase.genotype: the identified melting phase (het, wt, mut)


# What you care about is normd[[2]]:
meltinfo_volcano = normd_volcano[[2]]
meltinfo_volcano= merge(meltinfo_volcano, design_volcano) # Add design information

# Returns TRUE if there are any duplicates in "my_column"
meltinfo_volcano_testDup <- meltinfo_volcano %>% filter(normEBS.decrease!=0)
any(duplicated(meltinfo_volcano$normEBS.decrease))

library(dplyr)

#check for multiple occurrences of the same value (0 and 1 should be the only ones)
#we are checking this because multiple values of the inferred frequencies were found to be identical, which is strange considering the precision of the estimation (> 9 decimals)
table(meltinfo_volcano$normEBS.decrease)[table(meltinfo_volcano$normEBS.decrease) > 1]
#no issue at this point, 0 and 1 are the only values in multiple exemplaries

```

# Abnormal curve filtering

```{r}
#badscore function attribute a score indicating outlier curves (0 to 3; more is worst).
# +1 is being outside the 99% interval for the plateau_slope, max.fluo or het_decrease
meltinfo_volcano=badscore(meltinfo_volcano)
# To plot the metric distribution ~ of normEBS.decrease, use plot.bad
# Outlier in red; other samples in blue; calibration samples in black.
plot.bad(meltinfo_volcano) 

# You should get rid of the curve with a high badscore
badcurve_volcano = meltinfo_volcano$id[meltinfo_volcano$badscore>0 & is.na(meltinfo_volcano$calib)]
normd_volcano=subset.ID(normd_volcano, badcurve_volcano,out=T)
meltinfo_volcano = normd_volcano[[2]]
meltinfo_volcano= merge(meltinfo_volcano, design_volcano)

#You may want to look at the melting phase decomposition, especially for outliers
# It is possible that the algorithm did not decompose properly the melting curve
# If it is the case, you should also filter out these samples.
# Example: to look at the curve with id = "plate1#A19", you do:

# black --> calib sample
# red --> high badscore
# blue --> normal
plot.melting.phase(normd = normd_volcano, id = "plate2#A1")
plot.melting.phase(normd = normd_volcano, id = "plate1#A5")
plot.melting.phase(normd = normd_volcano, id = "plate1#A3")
plot.melting.phase(normd = normd_volcano, id = "plate1#B12")
# plot.melting.phase2(normd = normd, id = "plate1#A19") #Purple = heteroduplex; red = mutant; blue = wild-type.

#check for multiple occurrences of the same value (0 and 1 should be the only ones)
table(meltinfo_volcano$normEBS.decrease)[table(meltinfo_volcano$normEBS.decrease) > 1]
#same thing here, only 0 and 1 which is good.

save(meltinfo_volcano, file = "melting_volcano_info_example.Rdata")
```

# calibration train GAM

```{r}
#################################################################################
################### INFER REC-1 MUTANT FREQUENCY FROM DECREASE.NORMEBS ##########
#################################################################################

library(gam)
library(stringr)# Generalized additive model 
load("melting_volcano_info_example.Rdata")


# Calibration for competition 5
calib5 <- subset(meltinfo_volcano, calib == "calib"& competition =="5") %>%
  mutate(ratio = as.numeric(str_remove(ratio,"%"))/100)
# Train the model on the calibration samples
gam_model5 <-gam(ratio~s(normEBS.decrease, df=4)  ,data = calib5)
summary(gam_model5)

# If you want to plot the model
pgam5 =data.frame(xx=seq(0.0,1,0.01),
                 yy=predict(gam_model5, newdata = data.frame(normEBS.decrease=seq(0,1,0.01))) )


# Black line = model
# Dot are calibration samples; colors are independent calibration curves
p5 <- ggplot()+
  geom_point(data=calib5,
             aes(normEBS.decrease, ratio, color = ratio), shape=1, size=3,stroke=1)+
  annotate("text", x = 0.2, y = 1, label = "ECA722",
           color = "black", size = 10, alpha = 0.5) +
  coord_cartesian(clip = "off") +
  #theme_Publication2()+
  xlab(expression(d[mut]))+ylab("rec-1 mutant frequency")+
  theme(axis.title = element_text(size=17,colour = "black", face = "bold"),    
        axis.text = element_text(size=15, colour = "black"),
        strip.text = element_text(size = 15, color = "black", face = "bold"),
        plot.title = element_text(size = 17, hjust = -0.1, face = "bold"),
        legend.position = "none")+
  geom_line(data=pgam5, aes(x=xx, y=yy),size=1)+
  theme_bw()



# Calibration for competition 6
calib6 <- subset(meltinfo_volcano, calib == "calib"& competition =="6") %>%
  mutate(ratio = as.numeric(str_remove(ratio,"%"))/100)
# Train the model on the calibration samples
gam_model6 <-gam(ratio~s(normEBS.decrease, df=4)  ,data = calib6)
summary(gam_model5)

# If you want to plot the model
pgam6 =data.frame(xx=seq(0.0,1,0.01),
                 yy=predict(gam_model6, newdata = data.frame(normEBS.decrease=seq(0,1,0.01))) )


# Black line = model
# Dot are calibration samples; colors are independent calibration curves
p6 <- ggplot()+
  geom_point(data=calib6,
             aes(normEBS.decrease, ratio, color = ratio), shape=1, size=3,stroke=1)+
  annotate("text", x = 0.2, y = 1, label = "ECA191",
           color = "black", size = 10, alpha = 0.5) +
  coord_cartesian(clip = "off") +
  #theme_Publication2()+
  xlab(expression(d[mut]))+ylab("rec-1 mutant frequency")+
  theme(axis.title = element_text(size=17,colour = "black", face = "bold"),    
        axis.text = element_text(size=15, colour = "black"),
        strip.text = element_text(size = 15, color = "black", face = "bold"),
        plot.title = element_text(size = 17, hjust = -0.1, face = "bold"),
        legend.position = "none")+
  geom_line(data=pgam6, aes(x=xx, y=yy),size=1)+
  theme_bw()




# Calibration for competition 7
calib7 <- subset(meltinfo_volcano, calib == "calib"& competition =="7") %>%
  mutate(ratio = as.numeric(str_remove(ratio,"%"))/100)
# Train the model on the calibration samples
gam_model7 <-gam(ratio~s(normEBS.decrease, df=4)  ,data = calib7)
summary(gam_model7)

# If you want to plot the model
pgam7 =data.frame(xx=seq(0.0,1,0.01),
                 yy=predict(gam_model7, newdata = data.frame(normEBS.decrease=seq(0,1,0.01))) )


# Black line = model
# Dot are calibration samples; colors are independent calibration curves
p7 <- ggplot()+
  geom_point(data=calib7,
             aes(normEBS.decrease, ratio, color = ratio), shape=1, size=3,stroke=1)+
  annotate("text", x = 0.2, y = 1, label = "ECA730",
           color = "black", size = 10, alpha = 0.5) +
  coord_cartesian(clip = "off") +
  #theme_Publication2()+
  xlab(expression(d[mut]))+ylab("rec-1 mutant frequency")+
  theme(axis.title = element_text(size=17,colour = "black", face = "bold"),    
        axis.text = element_text(size=15, colour = "black"),
        strip.text = element_text(size = 15, color = "black", face = "bold"),
        plot.title = element_text(size = 17, hjust = -0.1, face = "bold"),
        legend.position = "none")+
  geom_line(data=pgam7, aes(x=xx, y=yy),size=1)+
  theme_bw()




# Calibration for competition 8
calib8 <- subset(meltinfo_volcano, calib == "calib"& competition =="8") %>%
  mutate(ratio = as.numeric(str_remove(ratio,"%"))/100)
# Train the model on the calibration samples
gam_model8 <-gam(ratio~s(normEBS.decrease, df=4) -1, data = calib8)
summary(gam_model8)

# If you want to plot the model
pgam8 =data.frame(xx=seq(0.0,1,0.01),
                 yy=predict(gam_model8, newdata = data.frame(normEBS.decrease=seq(0,1,0.01))) )


# Black line = model
# Dot are calibration samples; colors are independent calibration curves
p8 <- ggplot()+
  geom_point(data=calib8,
             aes(normEBS.decrease, ratio, color = ratio), shape=1, size=3,stroke=1)+
  annotate("text", x = 0.2, y = 1, label = "ECA723",
           color = "black", size = 10, alpha = 0.5) +
  coord_cartesian(clip = "off") +
  #theme_Publication2()+
  xlab(expression(d[mut]))+ylab("rec-1 mutant frequency")+
  theme(axis.title = element_text(size=17,colour = "black", face = "bold"),    
        axis.text = element_text(size=15, colour = "black"),
        strip.text = element_text(size = 15, color = "black", face = "bold"),
        plot.title = element_text(size = 17, hjust = -0.1, face = "bold"),
        legend.position = "none")+
  geom_line(data=pgam8, aes(x=xx, y=yy),size=1)+
  theme_bw()

p5
p6
p7
p8


```

## prediction

```{r}

#data = subset(meltinfo, is.na(calib)) #  unkown samples only for prediction
data_volcano = subset(meltinfo_volcano, is.na(calib))

library(dplyr)

data_volcano <- data_volcano %>% filter_out(is.na(normEBS.decrease))

# Initialize predicted_freq as a numeric vector with the same length as data_volcano
data_volcano$predicted_freq <- numeric(nrow(data_volcano))

# Loop over each level of competition
for (level in unique(data_volcano$competition)) {
  model_name <- paste0("gam_model", substr(level, 2, 2))  # Extract the number from V5, V6, etc.
  model <- get(model_name)  # Get the model object by name
  print(model_name)

  # Get the indices for the current level
  indices <- which(data_volcano$competition == level)
  print(indices)

  # Assign predictions to the correct indices
  data_volcano$predicted_freq[indices] <- predict(model, newdata = data_volcano[indices, ])
}



#A check for failed amplification was done because strange values were observed.

#check for multiple occurrences of the same value (0 and 1 should be the only ones)
table(data_volcano$normEBS.decrease)[table(data_volcano$normEBS.decrease) > 1]
table(data_volcano$predicted_freq)[table(data_volcano$predicted_freq) > 1]
#multiple occurrences of 4 values of predicted_freq

#see example with the most repeated value
volcano_duplicate <- data_volcano %>% filter(predicted_freq == 0.0714839560936415)

#it turns out that multiple wells failed amplification. They were removed from analysis.

save(data_volcano, file = "predicted_volcano_frequencies.Rdata")

```

## check calibration

```{r}
calib_pre <- data %>%
  filter(calib == "calib")
ggplot()+
  geom_point(data=calib_pre,
             aes(predicted_freq, ratio, color=ratio), shape=1, size=3,stroke=1)+
  #theme_Publication2()+
  xlab("predicted ratio")+ylab("rec-1 mutant frequency")+
  theme(axis.title = element_text(size=17,colour = "black", face = "bold"),    
        axis.text = element_text(size=15, colour = "black"),
        strip.text = element_text(size = 15, color = "black", face = "bold"),
        plot.title = element_text(size = 17, hjust = -0.1, face = "bold"),
        legend.position = "none")+
  theme_bw()
```

## check control: predicted frequencies must be null

```{r}
control_pre <- data %>%
  filter(calib == "control")
ggplot()+
  geom_point(data=control_pre,
             aes(predicted_freq, ratio), shape=1, size=3,stroke=1)+
  #theme_Publication2()+
  xlab("predicted ratio")+ylab("rec-1 mutant frequency")+
  theme(axis.title = element_text(size=17,colour = "black", face = "bold"),    
        axis.text = element_text(size=15, colour = "black"),
        strip.text = element_text(size = 15, color = "black", face = "bold"),
        plot.title = element_text(size = 17, hjust = -0.1, face = "bold"),
        legend.position = "none")+
  theme_bw()
```

```{r}
data_sample <- data %>%
  filter(is.na(calib))
str(data_sample)
data_sample$pop <- as.factor(data_sample$pop)
ggplot(
  data=data_sample, aes(x=generation, y=predicted_freq, group = pop))+
  geom_point(shape=1, size=3,stroke=1)+
  geom_line(data= data_sample, size = 0.5, aes(x=generation, y=predicted_freq))+
  #theme_Publication2()+
  xlab("generation")+ylab("rec-1 mutant frequency")+
  theme(axis.title = element_text(size=17,colour = "black", face = "bold"),    
        axis.text = element_text(size=15, colour = "black"),
        plot.title = element_text(size = 17, hjust = -0.1, face = "bold"),
        legend.position = "none")+
  theme_bw()

data_sample2 <- data_sample
data_sample2[, "replicate"] <- NA

data_sample2 <- data_sample2 %>%
  dplyr::group_by(pop, generation) %>%
  dplyr::mutate(replicate = dplyr::row_number()) %>%
  dplyr::ungroup()

data_sample2 <- data_sample2 %>% mutate(replicate=as.factor(replicate))
data_sample2 <- data_sample2 %>% mutate(generation=as.numeric(generation))
data_sample2 <- data_sample2[!is.na(data_sample2$pop), ]
data_sample2 <- data_sample2[!is.na(data_sample2$predicted_freq), ]

lineage_map <- data.frame(
  pop = c(
    "Z01","Z09","Z17","Z25",
    "Z02","Z10","Z18","Z26",
    "Z03","Z11","Z19","Z27",
    "Z04","Z12","Z20","Z28",
    "Z05","Z13","Z21","Z29",
    "Z06","Z14","Z22","Z30",
    "Z07","Z15","Z23","Z31",
    "Z08","Z16","Z24","Z32"
  ),
  lineage = c(
    rep("A",4),
    rep("B",4),
    rep("C",4),
    rep("D",4),
    rep("E",4),
    rep("F",4),
    rep("G",4),
    rep("H",4)
  )
)

lineage_map <- lineage_map %>% mutate(pop=as.factor(pop))
lineage_map <- lineage_map %>% mutate(lineage=as.factor(lineage))

data_sample <- data_sample %>%
  left_join(lineage_map, by = "pop")

ggplot(data_sample2,
       aes(x = generation,
           y = predicted_freq,
           group = interaction(pop, replicate),
           color = pop)) +
  geom_line(alpha = 0.3, size=1.5) +
  geom_point(alpha = 0.5, size=1.5) +
  theme_minimal()


ggplot()
```
